#!/usr/bin/env bash
# ─────────────────────────────────────────────────
# hfpclawer-cron-fetch.sh — Generated by 'hfpclawer cron init'
# Cron fetch script for Hermes no_agent=true mode (0 LLM tokens).
#
# Usage:
#   ./hfpclawer-cron-fetch.sh              # Human table (stderr)
#   ./hfpclawer-cron-fetch.sh --json       # JSON (stdout, for no_agent)
#   ./hfpclawer-cron-fetch.sh --help       # Help
#
# Crontab entry (run every Monday 18:59):
#   59 18 * * 1  /path/to/hfpclawer-cron-fetch.sh --json
# ─────────────────────────────────────────────────

set -euo pipefail

# ── Resolve script directory ──
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HFPCLAWER_DIR="$(dirname "$SCRIPT_DIR")"
DATA_DIR="${HFPCLAWER_DIR}/data"
SCRIPTS_DIR="${HFPCLAWER_DIR}/scripts"

# ── Environment ──
# Priority: HFPCLAWER_DATA env var > ~/.hfpclawer/data
HFPCLAWER_DATA="${HFPCLAWER_DATA:-$DATA_DIR}"
export HFPCLAWER_DATA

# Activate venv (auto-detect)
if command -v uv &>/dev/null && [ -f "${SCRIPT_DIR}/../../.venv/bin/activate" ]; then
    source "${SCRIPT_DIR}/../../.venv/bin/activate"
elif [ -f "${HFPCLAWER_DIR}/../.venv/bin/activate" ]; then
    source "${HFPCLAWER_DIR}/../.venv/bin/activate"
fi

# ── Parse args ──
OUTPUT_MODE="${1:-table}"
case "$OUTPUT_MODE" in
    --help|-h)
        echo "Usage: $(basename "$0") [--json|--help]"
        echo "  (no flag)  Output human-readable table to stderr"
        echo "  --json     Output JSON summary to stdout (for no_agent mode)"
        exit 0
        ;;
    --json|-j)
        hfpclawer cron run --json 2>&1
        ;;
    *)
        hfpclawer cron run 2>&1
        ;;
esac
