#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""cli_cron.py — hfpclawer cron {init,check,run,import} CLI subcommands.

Cron automation for periodic paper fetch + paper_store import.
Designed for both Hermes cron (LLM-driven) and no_agent=true (0 token) modes.

Typical no_agent cron setup:
  ~/.hfpclawer/scripts/hfpclawer-cron-fetch.sh  # Generated by 'cron init'
  59 18 * * 1  ~/.hfpclawer/scripts/hfpclawer-cron-fetch.sh  # Crontab entry
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

logger = logging.getLogger("hfpclawer.cli_cron")

# ─── Constants ────────────────────────────────────

HFPCLAWER_DIR = Path.home() / ".hfpclawer"
SCRIPTS_DIR = HFPCLAWER_DIR / "scripts"
DATA_DIR = HFPCLAWER_DIR / "data"
CONFIG_PATH = HFPCLAWER_DIR / "config.yaml"
SCRIPT_PATH = SCRIPTS_DIR / "hfpclawer-cron-fetch.sh"

# DB path resolution priority:
#   1. HFPCLAWER_DATA env var
#   2. ~/.hfpclawer/data/paper_store.db
DEFAULT_DB_PATH = DATA_DIR / "paper_store.db"

DEFAULT_CONFIG_YAML = """\
# hfpclawer cron config — generated by 'hfpclawer cron init'
# ─────────────────────────────────────────────────

# Search domains: one or more domain blocks (repeat the pattern below)
# Each domain gets its own arXiv query + paper_store source tag.
cron:
  domains:
    # ── ADD YOUR DOMAINS HERE ──
    # Examples:
    # - name: "gsnv"
    #   query: "cat:physics.ins-det+AND+abs:MFL"
    #   category: "gsnv"
    #
    # - name: "coc"
    #   query: "cat:physics.optics+AND+abs:optomechanic"
    #   category: "coc"

  # After fetch, run audit cron-verify (default: after each run)
  post_verify: true

# Environment (override via HFPCLAWER_DATA env var)
# data_dir: ~/my-custom-data-dir
"""

DEFAULT_SCRIPT_TEMPLATE = """\
#!/usr/bin/env bash
# ─────────────────────────────────────────────────
# hfpclawer-cron-fetch.sh — Generated by 'hfpclawer cron init'
# Runs paper fetch + import pipeline for configured domains.
# Designed for Hermes no_agent=true cron mode (0 LLM tokens).
#
# Usage:
#   ./hfpclawer-cron-fetch.sh              # Normal run, output table
#   ./hfpclawer-cron-fetch.sh --json       # Output JSON (for no_agent mode)
#   ./hfpclawer-cron-fetch.sh --help       # Show help
# ─────────────────────────────────────────────────

set -euo pipefail

# Resolve data directory
HFPCLAWER_DATA="${{HFPCLAWER_DATA:-{data_dir}}}"
export HFPCLAWER_DATA

# Venv activation (auto-detect: uv pipenv or bare)
if command -v uv &>/dev/null && [ -f "{project_root}/.venv/bin/activate" ]; then
    source "{project_root}/.venv/bin/activate"
elif command -v pipenv &>/dev/null && pipenv --venv &>/dev/null; then
    eval "$(pipenv shell --f)"
fi

OUTPUT_MODE="${{1:-table}}"
case "$OUTPUT_MODE" in
    --help|-h)
        echo "Usage: $(basename $0) [--json|--help]"
        echo "  (no flag)  Output human-readable table to stderr"
        echo "  --json     Output JSON summary to stdout (for no_agent mode)"
        exit 0
        ;;
    --json|-j)
        hfpclawer cron run --json 2>&1
        ;;
    *)
        # Human mode: show table, log stderr
        hfpclawer cron run 2>&1
        ;;
esac
"""


@dataclass
class CronRunResult:
    """Result of a single cron run."""

    domains_scanned: int = 0
    new_papers: int = 0
    updated_papers: int = 0
    errors: list[str] = field(default_factory=list)
    elapsed_s: float = 0.0

    def summary_line(self) -> str:
        return (
            f"cron: {self.domains_scanned} domains, "
            f"{self.new_papers} new, {self.updated_papers} updated, "
            f"{len(self.errors)} errors in {self.elapsed_s:.1f}s"
        )


# ─── Helpers ──────────────────────────────────────


def _resolve_db_path() -> Path:
    """Resolve paper_store.db path with 3-tier priority.

    1. HFPCLAWER_DATA env var → <env>/paper_store.db
    2. ~/.hfpclawer/data/paper_store.db (default)
    """
    env_data = os.environ.get("HFPCLAWER_DATA")
    if env_data:
        return Path(env_data).expanduser().resolve() / "paper_store.db"
    return DEFAULT_DB_PATH


def _domain_source_tag(name: str) -> str:
    """Create paper_store source tag for a domain."""
    return f"cron:{name}"


# ─── Actions ──────────────────────────────────────


def cron_init(
    name: str = "my-domain",
    query: str = "",
    keywords: str = "",
    from_config: str = "",
    data_dir: str = "",
    force: bool = False,
) -> str:
    """Initialize ~/.hfpclawer/ with config and scripts.

    Supports three search config modes:
      1. --query "cat:..."  — raw arXiv query
      2. --keywords "AI,ML"  — keyword-based (auto-converts to arXiv query)
      3. --from-config "/path/to/config.yaml" — use existing hfpclawer config
    """
    lines = []
    HFPCLAWER_DIR.mkdir(parents=True, exist_ok=True)
    SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    if custom_dir := data_dir:
        custom_data = Path(custom_dir).expanduser().resolve()
        custom_data.mkdir(parents=True, exist_ok=True)
        lines.append(f"📁 Data dir: {custom_data}")

    # ── Write config.yaml ──
    if CONFIG_PATH.exists() and not force:
        lines.append(f"ℹ️   Config exists: {CONFIG_PATH} (use --force to overwrite)")
    else:
        cfg = _build_config(name=name, query=query, keywords=keywords, from_config=from_config)
        CONFIG_PATH.write_text(cfg)
        lines.append(f"📝 Config: {CONFIG_PATH}")

    # ── Write shell script ──
    project_root = _detect_project_root()
    data_dir_str = str(DATA_DIR)
    if custom_dir:
        data_dir_str = str(Path(custom_dir).expanduser().resolve())

    script_content = DEFAULT_SCRIPT_TEMPLATE.format(
        data_dir=data_dir_str,
        project_root=project_root,
    )
    SCRIPT_PATH.parent.mkdir(parents=True, exist_ok=True)
    SCRIPT_PATH.write_text(script_content)
    SCRIPT_PATH.chmod(0o755)
    lines.append(f"🖥  Script: {SCRIPT_PATH}")

    # ── Summary ──
    lines.append("")
    lines.append("─── Setup complete ───")
    lines.append(f"  Config:     {CONFIG_PATH}")
    lines.append(f"  Script:     {SCRIPT_PATH}")
    lines.append(f"  Data dir:   {DATA_DIR}")
    lines.append(f"  Paper DB:   {DEFAULT_DB_PATH}")
    lines.append("")
    lines.append("Next steps:")
    lines.append(f"  1. Edit config: {CONFIG_PATH}")
    lines.append("     — Add your arXiv query(s) under cron.domains[]")
    lines.append("     — Set post_verify: true/false")
    lines.append("  2. Test fetch:")
    lines.append("     $ hfpclawer cron run")
    lines.append("  3. Set up crontab (for no_agent mode):")
    lines.append("     $ crontab -e")
    lines.append(f"     # Add: 59 18 * * 1  {SCRIPT_PATH}")
    lines.append("")
    lines.append("For Hermes cron (LLM-driven), create a cron job:")
    lines.append('  $ hermes cron create --schedule "0 18 * * 1" \\')
    lines.append('    --prompt "Run hfpclawer cron run and summarize new papers" \\')
    lines.append('    --skills hfpclawer-cron')

    return "\n".join(lines)


def cron_check() -> str:
    """Check cron configuration status."""
    lines = []
    lines.append("─── hfpclawer cron status ───")

    # Check HFPCLAWER_DIR
    if HFPCLAWER_DIR.exists():
        lines.append("✅ ~/.hfpclawer/     exists")
    else:
        lines.append("❌ ~/.hfpclawer/     missing (run 'hfpclawer cron init')")

    # Check config
    if CONFIG_PATH.exists():
        lines.append(f"✅ Config:          {CONFIG_PATH}")
    else:
        lines.append("❌ Config:          missing")

    # Check script
    if SCRIPT_PATH.exists():
        lines.append(f"✅ Script:          {SCRIPT_PATH}")
    else:
        lines.append("❌ Script:          missing (re-run 'cron init')")

    # Check DB
    db_path = _resolve_db_path()
    if db_path.exists():
        db_size = db_path.stat().st_size
        lines.append(f"✅ Paper DB:        {db_path} ({_fmt_size(db_size)})")
    else:
        lines.append(f"❌ Paper DB:        {db_path} (will be created on first run)")

    # Check crontab
    try:
        result = subprocess.run(["crontab", "-l"], capture_output=True, text=True, timeout=5)
        if result.returncode == 0 and "hfpclawer" in result.stdout:
            lines.append("✅ Crontab:         hfpclawer cron entry found")
            for line in result.stdout.splitlines():
                if "hfpclawer" in line:
                    lines.append(f"     {line.strip()}")
        else:
            lines.append("ℹ️   Crontab:         no hfpclawer entry")
    except Exception:
        lines.append("ℹ️   Crontab:         could not check")

    # Paper store stats (cron sources)
    try:
        from hfpapers.paper_store import get_store
        store = get_store()
        with store._conn() as conn:
            total = conn.execute(
                "SELECT COUNT(*) FROM papers WHERE source LIKE 'cron:%'"
            ).fetchone()[0]
            verified = conn.execute(
                "SELECT COUNT(*) FROM papers WHERE source LIKE 'cron:%' AND verified=1"
            ).fetchone()[0]
            by_domain = conn.execute(
                "SELECT source, COUNT(*) FROM papers WHERE source LIKE 'cron:%' GROUP BY source"
            ).fetchall()
        lines.append("")
        lines.append("📊 Paper Store (cron sources):")
        lines.append(f"    Total:     {total}")
        lines.append(f"    Verified:  {verified}")
        for row in by_domain:
            lines.append(f"    {row['source']}: {row['COUNT(*)']}")
    except Exception as e:
        lines.append(f"ℹ️   Paper Store:     {e}")

    return "\n".join(lines)


def cron_run(json_output: bool = False) -> str:
    """Execute cron pipeline: search → import into paper_store.

    Reads configured domains from ~/.hfpclawer/config.yaml,
    runs arXiv search for each domain, imports results with skip_crossref=True.
    """
    import yaml

    if not CONFIG_PATH.exists():
        return "❌ Config not found. Run 'hfpclawer cron init' first."

    cfg = yaml.safe_load(CONFIG_PATH.read_text())
    domains = cfg.get("cron", {}).get("domains", [])
    post_verify = cfg.get("cron", {}).get("post_verify", False)

    if not domains:
        return "❌ No domains configured in ~/.hfpclawer/config.yaml"

    from hfpapers.paper_store import ensure_paper
    from hfpapers.sources import ArxivApiSource

    result = CronRunResult()
    t0 = time.time()

    for domain in domains:
        name = domain.get("name", "unknown")
        query = domain.get("query", "")
        category = domain.get("category", "")

        if not query:
            result.errors.append(f"[{name}] no query configured")
            continue

        result.domains_scanned += 1

        # ── Search via arXiv API ──
        try:
            source = ArxivApiSource()
            papers = source.search(query=query, category=category)
        except Exception as exc:
            result.errors.append(f"[{name}] search failed: {exc}")
            continue

        if not papers:
            continue

        # ── Import into paper_store ──
        source_tag = _domain_source_tag(name)
        for paper in papers:
            try:
                sf_id, is_new = ensure_paper(
                    arxiv_id=paper.arxiv_id,
                    title=paper.title,
                    source=source_tag,
                    abstract=paper.abstract,
                    skip_crossref=True,
                    imported_via="hfpclawer@cron-run",
                )
                if is_new:
                    result.new_papers += 1
                else:
                    result.updated_papers += 1
            except Exception as exc:
                result.errors.append(f"[{name}] import {paper.arxiv_id}: {exc}")

    result.elapsed_s = time.time() - t0

    # ── Post-verify ──
    if post_verify and result.new_papers > 0:
        try:
            from hfpapers.paper_store import get_crossref, get_store
            from hfpclawer.audit.cron_verify import batch_verify
            store = get_store()
            cr = get_crossref()
            _ = batch_verify(store, cr, verbose=False)
        except Exception:
            pass  # Non-critical

    # ── Output ──
    if json_output:
        return json.dumps({
            "domains_scanned": result.domains_scanned,
            "new_papers": result.new_papers,
            "updated_papers": result.updated_papers,
            "error_count": len(result.errors),
            "errors": result.errors[:5],
            "elapsed_s": round(result.elapsed_s, 1),
            "timestamp": datetime.now().isoformat(),
        }, ensure_ascii=False, indent=2)
    else:
        lines = [
            f"─── cron run complete ({result.elapsed_s:.1f}s) ───",
            f"  Domains scanned: {result.domains_scanned}",
            f"  New papers:      {result.new_papers}",
            f"  Updated papers:  {result.updated_papers}",
            f"  Errors:          {len(result.errors)}",
        ]
        if result.errors:
            lines.append("  Errors:")
            for e in result.errors[:5]:
                lines.append(f"    ❌ {e}")
            if len(result.errors) > 5:
                lines.append(f"    ... and {len(result.errors) - 5} more")
        return "\n".join(lines)


def cron_import(
    source: str = "candidates",
    path: str = "",
    skip_crossref: bool = True,
) -> str:
    """Import existing papers into paper_store.

    Supports:
      - 'candidates': import from hfpclawer's candidates_latest.json
      - 'jsonl': import from a JSONL file (one JSON object per line)
      - 'arxiv-query': import results from an arXiv API query result file
    """
    import json as _json

    from hfpapers.paper_store import ensure_paper

    src_path = Path(path).expanduser().resolve() if path else None
    imported = 0
    skipped = 0
    errors = []

    if source == "candidates":
        # Import from candidate list (same format as hfpclawer search output)
        if not src_path:
            from hfpapers.config import get
            src_path = Path(get("paths.data_dir", "data")).expanduser() / "candidates_latest.json"
        if not src_path.exists():
            return f"❌ Candidates not found: {src_path}"
        with open(src_path) as f:
            candidates = _json.load(f)
        for paper in candidates if isinstance(candidates, list) else candidates.get("papers", []):
            try:
                aid = paper.get("arxiv_id", paper.get("id", ""))
                title = paper.get("title", "")
                if aid:
                    ensure_paper(arxiv_id=aid, title=title, source="cli:import",
                                 skip_crossref=skip_crossref)
                    imported += 1
            except Exception as e:
                errors.append(str(e))

    elif source == "jsonl":
        if not src_path or not src_path.exists():
            return f"❌ JSONL not found: {src_path}"
        with open(src_path) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = _json.loads(line)
                    aid = rec.get("arxiv_id", rec.get("id", ""))
                    title = rec.get("title", "")
                    if aid:
                        ensure_paper(arxiv_id=aid, title=title, source="cli:import",
                                     skip_crossref=skip_crossref)
                        imported += 1
                    else:
                        skipped += 1
                except Exception as e:
                    errors.append(str(e))

    else:
        return f"❌ Unknown source: {source} (use candidates|jsonl)"

    lines = ["─── Import complete ───"]
    lines.append(f"  Imported:    {imported}")
    lines.append(f"  Skipped:     {skipped}")
    lines.append(f"  Errors:      {len(errors)}")
    if errors:
        lines.append("  Sample errors:")
        for e in errors[:3]:
            lines.append(f"    ❌ {e}")
    return "\n".join(lines)


# ─── Internal helpers ─────────────────────────────


def _build_config(name: str, query: str, keywords: str, from_config: str) -> str:
    """Build config YAML content."""
    if from_config:
        src = Path(from_config).expanduser().resolve()
        if src.exists():
            return src.read_text()
        return f"# Config source not found: {from_config}\n" + DEFAULT_CONFIG_YAML

    if keywords:
        # Convert keywords to arXiv query (URL-encode spaces as +)
        terms = [k.strip().replace(" ", "+") for k in keywords.split(",") if k.strip()]
        query_parts = [f"abs:{t}" for t in terms]
        query = "+OR+".join(query_parts)

    if not query:
        query = "cat:cs.AI+AND+abs:neural+operator"

    import yaml
    cfg = {
        "cron": {
            "domains": [
                {"name": name, "query": query, "category": name},
            ],
            "post_verify": True,
        }
    }
    return yaml.safe_dump(cfg, default_flow_style=False, allow_unicode=True, sort_keys=False)



def _detect_project_root() -> str:
    """Find the hfpclawer project root dir."""
    # Check common locations
    candidates = [
        Path.home() / "Documents/Gitlab/Agentic4Sci/hfpapers-crawler",
        Path.home() / "Documents/Gitlab/forgejo-self-host/hfpapers-crawler",
        Path.cwd(),
    ]
    for d in candidates:
        if (d / "hfpapers").exists() and (d / "hfpclawer").exists():
            return str(d)
    # Fallback: try pip show
    try:
        import hfpclawer
        return str(Path(hfpclawer.__file__).parent.parent)
    except Exception:
        return str(Path.cwd())


def _fmt_size(size: int) -> str:
    for unit in ["B", "KB", "MB", "GB"]:
        if size < 1024:
            return f"{size:.1f}{unit}"
        size = size // 1024  # Use integer division
    return f"{size:.1f}TB"
